### ISSUE TITLE
miserable unbuffered write performance

### ISSUE THREAD

**Issue by lukts30** [GoogleChromeLabs/wasi-fs-access#1] opened 2020-11-04 13:03 UTC
I liked the idea of the project. So I compiled may program for wasi.
```
cargo wasi build --release
./wasm-opt --asyncify -O3 rdm4-bin.wasi.wasm -o rdm4.wasm
```
The problem is my program runs for about 120s (Windows 450ms and Linux 50 ms). On https://webassembly.sh/ it takes about 4s.
The problematic code was `serde_json::to_writer_pretty` (109KB output file). Using `BufWriter` made it comparable to the webassembly.sh runtime at least when using `navigator.storage.getDirectory()`. Writing to a real folder each new file `write_all` call takes additional ~1s.

---

So I tested on wasi.rreverser.com:

`dd if=/dev/urandom of=sample.data bs=1M count=10`

```
mount /tmp
mount /dst
```
- On Windows Chrome the `cp` command **can not copy files larger than 3MB** (Chromium on Linux works fine, but is super slow for an m.2 ssd ~2MB/s
- cat can copy a 20MB file even on Windows (`cat /tmp/sample.data > /dst/sample.test34`)

- Errors on Windows include:
  - An attempt was made to write to a file or directory which could not be modified due to the state of the underlying filesystem.
  - Cannot close a ERRORED writable stream

**Comment by RReverser** [comment] 2020-11-04 17:50
Do you have a source for your program? Otherwise it's hard to tell what it does from just a command. In general, however, webassembly.sh is certainly not comparable to wasi.rreverser.com, because the latter one uses an _actual_ filesystem, with corresponding I/O costs.

If your code does not utilise, for example, `BufWriter`, and instead writes to a `File` directly, then this is a known performance issue with Rust in general, and can make code terribly slow as each write operation results in a syscall (which are even more expensive in our simulated WASI environment).

As for Windows issues - interesting, I don't think I've encountered those, but if you can reproduce them with pure File System Access API, it would be great if you could submit an issue to crbug.com - someone from their team should be able to take a look.

**Comment by lukts30** [comment] 2020-11-04 20:39
My bad for not using BufWriter for the small JSON file. Traditional syscall for such a small file are too cheap to even notice it. Windows and Linux performance is unchanged.

---
>because the latter one uses an actual filesystem, with corresponding I/O costs.

Writing to the `navigator.storage.getDirectory()` backed /sandbox is still a lot faster compared to mounted folders. With BufWriter the program now needs 1-2s on /sandbox. With a real folder each new file cost 0.5-1s and since 10 files (each ~1MB) are written the whole program now takes 10-15s. That's too long since the written files (gltf 3D model) should be immediately displayed with an embedded Babylon.js Viewer.
Since the runtime when writing to /sandbox is acceptable I already considering buffering all writes there. Display the /sandbox file while simultaneously copying them to the real mounted path.

The Windows issues are reproducible for me with both Chrome 86.0.4240.183 and Canary 88.0.4315.3. The max size they are able to copy seems to fluctuate. Now it stops at 20MB, but yesterday everything above 3 MB would fail.
I don't know of a pure javascript File System Access API demo to test with that writes more than a few MB.

**Comment by RReverser** [comment] 2020-11-04 21:23
> Traditional syscall for such a small file are too cheap to even notice it. Windows and Linux performance is unchanged.

Interesting. I've definitely seen native performance getting an order of magnitude better with `BufWriter` / `BufReader` even on native systems, but it does depend on writing patterns of a particular app. Anyway, glad it helped.

> The max size they are able to copy seems to fluctuate. Now it stops at 20MB, but yesterday everything above 3 MB would fail.

Ah. Do this errors by any chance occur specifically in `/sandbox` folder and not in a real filesystem? If so, the fact that it fluctuates sounds like it might be per-origin storage limits kicking in, which are based in browsers on a lot of heuristics (including kind of origin, amount of total free space on disk, etc.).

I'm also on Windows and I just tried and successfully copied 100MB from my mounted folder into a sandbox. (I do agree that it was slow, but tbh I didn't spend _too_ much effort optimising those parts - if it's something you're interested in, contributions are certainly welcome!).

Can you perhaps open DevTools and check a result of `await navigator.storage.estimate()`? Not sure how accurate it is, but it might be telling if the `quota` part of the result is very low.

**Comment by lukts30** [comment] 2020-11-04 21:39
>Ah. Do this errors by any chance occur specifically in /sandbox folder and not in a real filesystem? If so, the fact that it fluctuates sounds like it might be per-origin storage limits kicking in, which are based in browsers on a lot of heuristics (including kind of origin, amount of total free space on disk, etc.).

The windows, chrome issues only happen when writing to a real folder. I can copy a 100MB file from my an mounted folder to sandbox, but not the other way around. Neither can I copy from my mounted folder to same or other mounted the folder. They fail wtih _An attempt was made to write to a file or directory which could not be modified due to the state of the underlying filesystem._

**Comment by lukts30** [comment] 2020-11-04 22:07
In the devtools console there is also:  
```
DOMException: A requested file or directory could not be found at the time an operation was processed.
translateError @ bindings.ts:833
```

And brute force copy also works. Slightly **confused** ...
```
$ mount /tmp
Successfully mounted (...host path...)/tmp at /tmp.
$ cp /sandbox/hundert /tmp/ziel 
An attempt was made to write to a file or directory which could not be modified due to the state of the underlying filesystem.
$ cp /sandbox/hundert /tmp/ziel 
An attempt was made to write to a file or directory which could not be modified due to the state of the underlying filesystem.
$ cp /sandbox/hundert /tmp/ziel2
$ ls -lah /tmp
drw-rw- 1 somebody somegroup       0 1970-01-01 00:00 .
ls: error: ..: Capabilities insufficient (os error 76)
-rw-rw- 1 somebody somegroup       0 2020-11-04 22:04 ziel
-rw-rw- 1 somebody somegroup   1.97M 2020-11-04 22:04 ziel.1.crswap
-rw-rw- 1 somebody somegroup   1.90M 2020-11-04 22:04 ziel.crswap
-rw-rw- 1 somebody somegroup 104.86M 2020-11-04 22:05 ziel2
```

**Comment by RReverser** [comment] 2020-11-04 23:02
> Also, I than tried and created a second partition an mounted that and it work flawlessly! Who's at fault here? Windows, Chrome or my hardware ?

Honestly - no idea... I'd probably go back to my suggestion to try and reproduce this with pure JS to pinpoint the problem (at least to exclude the WASI layer).

You can try to play with variations of code like this in DevTools console and see if it exhibits same issues:

```js
let f = await showSaveFilePicker();
let w = await f.createWritable();
await w.write(new Uint8Array(/* size */ 10 * 1024 * 1024));
await w.close()
```

**Comment by lukts30** [comment] 2020-11-05 12:35
```js
let f = await showSaveFilePicker();
let w = await f.createWritable();
let array = new Uint8Array(8*1024); // matches rust current default of 8 KB
window.crypto.getRandomValues(array);
for(let i=0;i<12_800;i++) { await w.write(array); } // 100 MiB
await w.close()
```

I ran the javascript code and it worked, but after that `cp` also suddenly started to work.
It seems to be caused by **Windows Defender**. It was the whole time enabled even when `cp` magically started working.

But even with it now working I can 100% reproduce the error in a fresh VM. In this new VM `cp` is also worked out of the box, but if I open the mounted folder in Windows explorer and right click properties on the .crswap file Chrome stops writing and raises a DOMException. Clicking on properties with Defender disabled works fine.

I can additionally trigger the exception if I try to copy an unsigned executable PE file (no right click properties required).

```
DOMException: A requested file or directory could not be found at the time an operation was processed.
translateError @ bindings.ts:833
```

**Comment by RReverser** [comment] 2020-11-05 12:51
Interesting. If you want, you can try to change code above to something like:

```js
let f = await showSaveFilePicker();
let w = await f.createWritable();
let array = new Uint8Array(8*1024); // matches rust current default of 8 KB
window.crypto.getRandomValues(array);
while (true) await w.write({ type: 'write', position: 0, data }); // keep writing to the same file at the start
```

This will limit the file size to your 8 KB, but keep writing to it over and over, hopefully producing same pattern as `cp`. If you can reproduce the issues with Defender (by right-clicking the file etc.) with code above, it should be a sufficient example to submit to crbug.com.

I think in general it wouldn't be the first software to run into similar issues with Defender, e.g. Rustup has been suffering from it for a while and eventually had to add a simple retry functionality to write several time until it succeeds. In this case the solution should probably be the same, but I'm not sure whether File System Access API considers it to be something that consumers should handle on their own, or something that should be done by an implementer of the API (the browser). Either way, we need to get a reproducible example first to start a discussion on the bug tracker.

**Comment by lukts30** [comment] 2020-11-05 15:56
Little update:
The right click properties is not necessary Defender related. But it follows the same pattern as Defender. Chrome ends up with an. `STATUS_SHARING_VIOLATION`. Same results with both Windows 2004 & 1903.

This is when it is successful:
```
16:21:57,4170480	chrome.exe	4128	CreateFile	C:\Users\lukas\Desktop\Neuer Ordner\neww.crswap	SUCCESS	Desired Access: Generic Write, Read Attributes, Disposition: Open, Options: Non-Directory File, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
16:21:57,4171573	chrome.exe	4128	WriteFile	C:\Users\lukas\Desktop\Neuer Ordner\neww.crswap	SUCCESS	Offset: 0, Length: 8.192, Priority: Normal
16:21:57,4173268	chrome.exe	4128	CloseFile	C:\Users\lukas\Desktop\Neuer Ordner\neww.crswap	SUCCESS	
```

And with Defender this happens sometimes (not all the time).  I will try to make it better reproducible. 
```
16:21:57,4196785	MsMpEng.exe	2408	CreateFileMapping	C:\Users\lukas\Desktop\Neuer Ordner\neww.crswap	FILE LOCKED WITH ONLY READERS	SyncType: SyncTypeCreateSection, PageProtection: PAGE_EXECUTE|PAGE_NOCACHE
16:21:57,4197005	MsMpEng.exe	2408	QueryStandardInformationFile	C:\Users\lukas\Desktop\Neuer Ordner\neww.crswap	SUCCESS	AllocationSize: 8.192, EndOfFile: 8.192, NumberOfLinks: 1, DeletePending: False, Directory: False
16:21:57,4199508	chrome.exe	4128	CreateFile	C:\Users\lukas\Desktop\Neuer Ordner\neww.crswap	SHARING VIOLATION	Desired Access: Generic Write, Read Attributes, Disposition: Open, Options: Non-Directory File, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
```

This is explorer just clicking properties: 
```
14:13:33,7640091	MsMpEng.exe	3924	CreateFileMapping	C:\Users\lukas\Desktop\ziel\twerg.crswap	FILE LOCKED WITH WRITERS	SyncType: SyncTypeCreateSection, PageProtection: PAGE_EXECUTE|PAGE_NOCACHE
14:13:33,7640250	MsMpEng.exe	3924	QueryStandardInformationFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	AllocationSize: 8.192, EndOfFile: 8.192, NumberOfLinks: 1, DeletePending: False, Directory: False
14:13:33,7641757	MsMpEng.exe	3924	QueryNameInformationFile	C:\Users\lukas\AppData\Local\Google\Chrome SxS\Application\chrome.exe	SUCCESS	Name: \Users\lukas\AppData\Local\Google\Chrome SxS\Application\chrome.exe
14:13:33,7645258	Explorer.EXE	5576	CreateFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
14:13:33,7645469	Explorer.EXE	5576	QueryBasicInformationFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	CreationTime: 05.11.2020 14:13:22, LastAccessTime: 05.11.2020 14:13:33, LastWriteTime: 05.11.2020 14:13:33, ChangeTime: 05.11.2020 14:13:33, FileAttributes: A
14:13:33,7645566	Explorer.EXE	5576	CloseFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	
14:13:33,7645726	Explorer.EXE	5576	NotifyChangeDirectory	C:\Users\lukas\Desktop\ziel		Filter: FILE_NOTIFY_CHANGE_FILE_NAME, FILE_NOTIFY_CHANGE_ATTRIBUTES, FILE_NOTIFY_CHANGE_LAST_WRITE
14:13:33,7646515	Explorer.EXE	5576	CreateFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
14:13:33,7646964	Explorer.EXE	5576	QueryStandardInformationFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	AllocationSize: 8.192, EndOfFile: 8.192, NumberOfLinks: 1, DeletePending: False, Directory: False
14:13:33,7647132	Explorer.EXE	5576	CreateFileMapping	C:\Users\lukas\Desktop\ziel\twerg.crswap	FILE LOCKED WITH ONLY READERS	SyncType: SyncTypeCreateSection, PageProtection: PAGE_EXECUTE_READWRITE
14:13:33,7647237	Explorer.EXE	5576	QueryStandardInformationFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	AllocationSize: 8.192, EndOfFile: 8.192, NumberOfLinks: 1, DeletePending: False, Directory: False
14:13:33,7647412	Explorer.EXE	5576	CreateFileMapping	C:\Users\lukas\Desktop\ziel\twerg.crswap	SUCCESS	SyncType: SyncTypeOther
14:13:33,7647483	Explorer.EXE	5576	NotifyChangeDirectory	C:\Users\lukas\Desktop		Filter: FILE_NOTIFY_CHANGE_FILE_NAME, FILE_NOTIFY_CHANGE_ATTRIBUTES, FILE_NOTIFY_CHANGE_LAST_WRITE
14:13:33,7648027	chrome.exe	11224	CreateFile	C:\Users\lukas\Desktop\ziel\twerg.crswap	SHARING VIOLATION	Desired Access: Generic Write, Read Attributes, Disposition: Open, Options: Non-Directory File, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
```

**Comment by lukts30** [comment] 2020-11-05 18:42
I think I understand the problem with the current implementiotion in Chrome . A single `await w.write(...)` works always. But for each write Chrome calls CreateFile,WriteFile and **CloseFile**! Chrome correctly locks the file, but it releases the file handle even though **w.close()** was not yet called. Because now the file is not locked another process can come along and open it with exclusive access. For the next `await w.write(...)` call Chrome calls CreateFile which returns STATUS_SHARING_VIOLATION.

I think in general Chrome should just keep the file handle open. File access is expensive on Windows and since my initial program to test did not use BufWriter Chrome would for each write call call CreateFile, WriteFile and **CloseFile**. This would also explain the 120s needed to run even though a normal unbuffered run on Windows takes only 0.5s.

---

Reproducible without depending on the nondeterministic explorer.exe or MsMpEng.exe locking urge.

In Chrome run:
```js
let f = await showSaveFilePicker();
let w = await f.createWritable();
let array = new Uint8Array(8*1024);
window.crypto.getRandomValues(array);
while (true) await w.write({ type: 'write', position: 0, data: array }); //keep writing to the same file at the start
```

And open powershell edit `fileName` and run: 
```ps1
$fileName = "C:\Users\lukas\Desktop\chrome\test.crswap"
while($true){ 
	try { 
		$file = [System.io.File]::Open($fileName, 'Open', 'Read', 'None');
		echo "Succeed! Locking the file for 10s!"
		Start-Sleep -Seconds 10
		#Close the file (This releases the current handle and unlocks the file)
		$file.Close()
		break
	} catch { echo "file is locked trying again" }
}
```
_[1] https://superuser.com/questions/857725/how-to-lock-a-file-in-windows-without-changing-it-or-using-third-party-tools_

**Comment by RReverser** [comment] 2020-11-05 19:55
@lukts30 Makes sense. Unfortunately, I don't work on the Chrome implementation of the API, I've only used it for the demo, so it would be helpful if you could report your findings to crbug.com. (I think your details and repro code above would be enough to just copy verbatim.)

**Comment by lukts30** [comment] 2020-11-05 20:44
@RReverser 
I have created a report on crbug.com. I am new to that reporting process hope it has all the necessary information. 

https://bugs.chromium.org/p/chromium/issues/detail?id=1146149

**Comment by RReverser** [comment] 2020-11-05 21:49
@lukts30 Thanks. Looks good to me, but let's see what engineers on the implementation side say. The only thing I've changed is also added FileSystem component to make the issue more easily discoverable.

**Comment by RReverser** [comment] 2020-11-07 22:19
I'll close the issue here as, IIUC, there's no issue with wasi-fs-access itself. Optimisation PRs are always welcome though!

**Closed by RReverser** 2020-11-07 22:19 UTC

**Comment by RReverser** [comment] 2020-11-07 22:21
Btw, I wonder if performance issues described above are also caused by Defender interfering with the file (well, and also by Chrome closing/re-opening file over and over too). Perhaps try disabling it for the given target folder and checking if it helps at all?
